-- Write code here or enter directly in PostgreSQL shell --
-- \l to bring up data base
-- DROP DATABASE IF EXISTS sample_db; to delete database
-- CREATE DATABASE books_db; to create database (for books)
-- \c books_db to connect to database
-- or SELECT current_database();